server {
    listen 80;
    server_name unl-cloud-connect.me;
    
    # Redirigir todo el tráfico HTTP a HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name unl-cloud-connect.me;

    # Rutas de los certificados SSL que montaremos desde la Máquina Virtual
    ssl_certificate /etc/letsencrypt/live/unl-cloud-connect.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/unl-cloud-connect.me/privkey.pem;

    # Opciones de seguridad recomendadas
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    # Servir el frontend React (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy inverso: redirige /api/* al API Gateway (Kong)
    location /api/ {
        proxy_pass http://unl_api_gateway:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
